"""Initial migration

Revision ID: e002a00998a6
Revises:
Create Date: 2020-06-22 09:53:21.521618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e002a00998a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hrsa_designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('abv', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abv', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hrsa_id', sa.String(), nullable=True),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('hrsa_designation_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('full_year', sa.Integer(), nullable=True),
    sa.Column('opa_findings', sa.String(), nullable=True),
    sa.Column('sanction', sa.String(), nullable=True),
    sa.Column('cap_status', sa.String(), nullable=True),
    sa.Column('closure_date', sa.Date(), nullable=True),
    sa.Column('entity_contact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hrsa_designation_id'], ['hrsa_designations.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('states')
    op.drop_table('hrsa_designations')
    # ### end Alembic commands ###
